swagger: '2.0'
info:
  version: '1.0'
  title: "iProjectIS2"
  description: Api's for the project.
host: iprojectis2.herokuapp.com
basePath: "/v1"
tags: 
- name: "Professor"
- name: "Student"
- name: "Test"
- name: "Exam"
- name: "Assignment"
- name: "Workgroup"
- name: "Workgroup's Post"
- name: "Book"
- name: "Course"
- name: "Delivery"

  
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:

  /professors:
    x-summary: /professors
    get:
      tags: 
        - "Professor"
      summary: List of Professors
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idProfessor"
        type: "integer"
      - in: "query"
        name: "nameProfessor"
        type: "string"
      - in: "query"
        name: "emailProfessor"
        type: "string"

      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Professors"


    post:
      summary: Create Professor
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Professors object"
        required: true
        schema:
          $ref: "#/definitions/Professors" 
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Professor
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Professor"
        required: true
        schema:
          $ref: "#/definitions/Professors"

      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid test supplied"
        404:
          description: "Test not found"
  
  /professors/{idProfessor}:
    
    delete:
      tags: 
        - "Professor"
      summary: Delete Professor By Id
      operationId: "DeleteProfessorById"
      produces: 
      - "application/json"
      parameters:
      - name: "idProfessor"
        in: "path"
        description: "Professor id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'


  /students:
    x-summary: /students
    get:
      tags: 
        - "Student"
      summary: List of Students
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idStudent"
        type: "integer"
      - in: "query"
        name: "nameStudent"
        type: "string"
      - in: "query"
        name: "emailStudent"
        type: "string"
      
      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Students"


    post:
      summary: Create Student
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object"
        required: true
        schema:
          $ref: "#/definitions/Students" 
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Student
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Student"
        required: true
        schema:
          $ref: "#/definitions/Students"
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid test supplied"
        404:
          description: "not found"
    
  /students/{idStudent}:
    delete:
      tags: 
        - "Student"
      summary: Delete Student By Id
      operationId: "DeleteStudentById"
      produces: 
      - "application/json"
      parameters:
      - name: "idStudent"
        in: "path"
        description: "Student id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'


  /tests:
    x-summary: /tests
    get:
      tags: 
        - "Test"
      summary: List of Tests
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idTest"
        type: "integer"
      - in: "query"
        name: "nameTest"
        type: "string"

      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tests"
          

    post:
      summary: Create Test
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Test object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Tests" 
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"
           
 
    put:
      summary: Update Test
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Test"
        required: true
        schema:
          $ref: "#/definitions/Tests"

      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid test supplied"
        404:
          description: "not found"
          examples:
            application/json: 
            
  /tests/{idTest}:
    delete:
      tags: 
        - "Test"
      summary: Delete Test By Id
      operationId: "DeleteTestById"
      produces: 
      - "application/json"
      parameters:
      - name: "idTest"
        in: "path"
        description: "Test id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

  /exams:
    x-summary: /exams
    get:
      tags: 
        - "Exam"
      summary: List of Exams
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idExams"
        type: "integer"
      - in: "query"
        name: "nameExams"
        type: "string"
      - in: "query"
        name: "idTest"
        type: "integer"
      - in: "query"
        name: "idProfessor"
        type: "integer"
      - in: "query"
        name: "nameProfessor"
        type: "string"
      - in: "query"
        name: "idCourse"
        type: "integer"
      - in: "query"
        name: "nameCourse"
        type: "string"
      - in: "query"
        name: "exam-type"
        type: "string"
        enum:
        - "oral"
        - "write"
        - "practical"
      responses:
        200:
          description: 'Successful Response'
          schema: 
            type: "array"
            items:
              $ref: "#/definitions/Exams"
    post:
      summary: Create Exam
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Exam object that needs to be added"
        schema:
          $ref: "#/definitions/Exams"
         
      responses:
        201:
          description: 'Succesful'
        405:
          description: "Invalid input"
            
    put:
      summary: Update Exams
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Exam"
        schema:
          $ref: "#/definitions/Exams"
      responses:
        201:
          description: 'Valid'
        400:
          description: "Invalid exam supplied"
        404:
          description: "Exam not found"
          
  /exams/{idExam}:
    delete:
      tags: 
        - "Exam"
      summary: Delete Exam By Id
      operationId: "DeleteExamById"
      produces: 
      - "application/json"
      parameters:
      - name: "idExam"
        in: "path"
        description: "Exam id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'


  /assignments:
    x-summary: /assignments
    get:
      tags: 
        - "Assignment"
      summary: List of Assignments
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idAssignments"
        type: "integer"
      - in: "query"
        name: "nameAssignments"
        type: "string"
      - in: "query"
        name: "idTest"
        type: "integer"
      - in: "query"
        name: "idProfessor"
        type: "integer"
      - in: "query"
        name: "nameProfessor"
        type: "string"
      - in: "query"
        name: "idCourse"
        type: "integer"
      - in: "query"
        name: "nameCourse"
        type: "string"
      - in: "query"
        name: "obligatory"
        type: "boolean"

      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Assignments"


    post:
      summary: Create Assignment
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Assignments object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Assignments" 
          
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Assignment
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Test"
        required: true
        schema:
          $ref: "#/definitions/Assignments"
         
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid assignment supplied"
        404:
          description: "Assignment not found"
          
  /assignments/{idAssignment}:
    delete:
      tags: 
        - "Assignment"
      summary: Delete Assigment By Id
      operationId: "DeleteAssignmentById"
      produces: 
      - "application/json"
      parameters:
      - name: "idAssignment"
        in: "path"
        description: "Assignment id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

  /workgroups:
    x-summary: /workgroups
    get:
      tags: 
        - "Workgroup"
      summary: List of Workgroups
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idWorkgroup"
        type: "integer"
      - in: "query"
        name: "nameWorkgroup"
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Workgroups"

    post:
      summary: Create Workgroup
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Workgroups object"
        required: true
        schema:
          $ref: "#/definitions/Workgroups" 
         
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Workgroup
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Workgroup"
        required: true
        schema:
          $ref: "#/definitions/Workgroups"
         
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid"
        404:
          description: " not found"
          
  /workgroups/{idWorkgroup}:
    delete:
      tags: 
        - "Workgroup"
      summary: Delete Workgroup By Id
      operationId: "DeleteWorkgroupById"
      produces: 
      - "application/json"
      parameters:
      - name: "idWorkgroup"
        in: "path"
        description: "Workgroup id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

  /workgroups/idWorkgroup/posts:
    x-summary: /workgroups/{idWorkgroup}/posts
    get:
      tags: 
        - "Workgroup's Post"
      summary: List of Posts in a Workgroup
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idWorkgroup"
        type: "integer"
      - in: "query"
        name: "nameWorkgroup"
        type: "string"
      - in: "query"
        name: "idPost"
        type: "integer"
 
      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Workgroups|idWorkgoup|posts"


    post:
      summary: Create Posts in Workgroup 
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Workgroups/object object"
        required: true
        schema:
          $ref: "#/definitions/Workgroups|idWorkgoup|posts" 
      
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Post in Workgroup
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Workgroups/object object"
        required: true
        schema:
          $ref: "#/definitions/Workgroups|idWorkgoup|posts" 
         
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid"
        404:
          description: "not found" 
          
  /workgroups/posts/{idPost}:
    delete:
      tags: 
        - "Workgroup's Post"
      summary: Delete Workgroup's Post By Id
      operationId: "DeleteWorkgroup'sPostById"
      produces: 
      - "application/json"
      parameters:
      - name: "idPost"
        in: "path"
        description: "Post id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

  /books:
    x-summary: /books
    get:
      tags: 
        - "Book"
      summary: List of Books
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idBook"
        type: "integer"
      - in: "query"
        name: "title"
        type: "string"
      - in: "query"
        name: "idCourse"
        type: "integer"

      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Books"


    post:
      summary: Create Book
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object"
        required: true
        schema:
          $ref: "#/definitions/Books" 
      
         
      responses:
        201:
          description: 'succesful'
        405:
          description: "Invalid input"

    put:
      summary: Update Book
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Books object"
        required: true
        schema:
          $ref: "#/definitions/Books" 
          
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid "
        404:
          description: "not found"
          
  /books/{idBook}:
    delete:
      tags: 
        - "Book"
      summary: Delete Book By Id
      operationId: "DeleteBookById"
      produces: 
      - "application/json"
      parameters:
      - name: "idBook"
        in: "path"
        description: "Book id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

            
  /courses:
    x-summary: /courses
    get:
      tags: 
        - "Course"
      summary: List of Courses
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idCourse"
        type: "integer"
      - in: "query"
        name: "nameCourse"
        type: "string"
      - in: "query"
        name: "idProfessor"
        type: "integer"

      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Courses"


    post:
      summary: Create Course
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Course object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Courses" 
         
      responses:
        201:
          description: 'successful'
        405:
          description: "Invalid input"

    put:
      summary: Update Course
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Update Test"
        required: true
        schema:
          $ref: "#/definitions/Courses"
         
      responses:
        201:
          description: 'valid'
        400:
          description: "Invalid course supplied"
        404:
          description: "Course not found"

  /courses/{idCourse}:
    delete:
      tags: 
        - "Course"
      summary: Delete Course By Id
      operationId: "DeleteCourseById"
      produces: 
      - "application/json"
      parameters:
      - name: "idCourse"
        in: "path"
        description: "Course id to delete"
        required: true
        type: "integer"
        
      responses:
        204: 
          description: 'successful'
        400:
          description: 'Invalid ID'
        404: 
          description: 'not found'

  /delivery:
    x-summary: /deliveries
    get:
      tags: 
        - "Delivery"
      summary: List of Delivery
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "idDelivery"
        type: "integer"
      - in: "query"
        name: "idStudent"
        type: "integer"
      - in: "query"
        name: "idExam"
        type: "integer"
      responses:
        200:
          description: Successful Response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Deliveries"
    post:
      summary: Create Delivery
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Delivery object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Deliveries" 
         
      responses:
        201:
          description: 'successful'
        405:
          description: "Invalid input"

definitions:

  Students:
    type: "object"
    properties:
      idStudent:
        type: "integer"
      nameStudent:
        type: "string"
      emailStudent: 
        type: "string"
        format: "email"
      password:
        type: "string"
    required:
      - idStudent
      - nameStudent
    example:
      idStudent: 753847
      nameStudent: "Alessandro"
      emailStudent: "alessandro.wioqe@sue.com"
      password: "Pkejfwie84"

  Professors:
    type: "object"
    properties:
      idProfessor:
        type: "integer"
      nameProfessor:
        type: "integer"
      emailProfessor:
        type: "string"
        format: "email"
      password:
        type: "string"
    required: 
      - idProfessor
      - nameProfessor 
    example: 
      idProfessor: 12273
      nameProfessor: "Matteo"
      emailProfessor: "matteo.ghgh@ueh.com"
      password: "SedqjER-2jhd"

  Tests: 
    type: "object"
    properties:
      idTest:
        type: "integer"
      nameTest: 
        type: "string"
      questions:
        type: "array"
        items: 
          type: "object"
          properties:
            idQuestion:
              type: "integer"
    required: 
      - idTest
      - nameTest
    example:
      idTest: 28939123
      nameTest: analisi
      questions: [918239,10293810,123810,12831]



  Exams: 
    type: "object"
    properties:
      idExam:
        type: "integer"
      nameExam: 
        type: "string"
      idProfessor:
        type: "integer"
      idCourse: 
        type: "integer"
      idTest:
        type: "integer"
      deadline:
        type: "string"
        format: "date-time"
      examType:
        type: "string"
        description: "Type of Exam"
        enum:
          - "oral"
          - "write"
          - "practical"
      description:
        type: "string"
    required:
      - idExam
      - nameExam
      - idProfessor
      - idCourse
      - idTest
      - deadline 
      - examType
      
    example:
      idExam: 9283091
      nameExam: "analisi 1"
      idProfessor: 1672488
      idCourse: 8823749
      idTest: 58379842
      deadline: "2018-12-06 12:34:21"
      examType: 'oral'
      description: "gfuytjftesythjhtfyghhkuiygfyrsawrsfdhfj"
      

  Assignments:
    type: "object"
    properties:
      idAssignment:
        type: "integer"
      nameAssignment: 
        type: "string"
      idTest:
        type: "integer"
      idProfessor:
        type: "integer"
      idCourse: 
        type: "integer"
      deadline:
        type: "string"
        format: "date-time"
      obligatory:
        type: "boolean"
        default: false
      descriprion:
        type: "string"
    required:
      - idAssignment
      - nameAssignment
      - idTest
      - idProfessor
      - idCourse
      - deadline
      - obligatory
    example: 
      idAssignment: 9283091
      nameAssignment: "assignment 1"
      idProfessor: 1672488
      idCourse: 8823749
      idTest: 58379842
      deadline: "2018-12-06 12:34:21"
      obligatory: true
      description: "wqhjfghjqwhfiuqwfio"

  Workgroups:
    type: "object"
    properties:
      idWorkgroup:
        type: "integer"
      nameWorkgroup: 
        type: "string"
      Members:
        type: "array"
        items: 
          type: "object"
          properties:
            idStudent:
              type: "integer"
    required:
      - idWorkgroup
      - nameWorkgroup
      - Members
    example:
      idWorkgroup: 2988497
      nameWorkgroup: "iProjectIS2"
      Members: array
            
  Workgroups|idWorkgoup|posts:
    type: "object"
    properties:
      idWorkgroup:
        type: "integer"
      idPost:
        type: "integer"
      Posts:
        type: "array"
        items: 
          type: "object"
          properties:
            idStudent:
              type: "integer"
            message: 
              type: "string"
    required:
      - idWorkgroup
      - idPost
    example: 
      idWorkgroup: 18381783
      idPost: 27378
      Posts: array
  
  Books:
    type: "object"
    properties:
      idBook:
        type: "integer"
      title: 
        type: "string"
      idStudent:
        type: "integer"
      idCourse: 
        type: "integer"
      sold:
        type: "boolean"
        default: false
      deadline: 
        type: "string"
        format: "date-time"
    required: 
      - idBook
      - idStudent
      - deadline 
      - sold
    example:
      idBook: 34290239
      title: "cavanda & Co."
      idStudent: 567320
      idCourse: 6948248
      sold: "false"
      deadline: "2018-12-13 14:07:56"
 
  Courses:
    type: "object"
    properties:
      idCourse:
        type: "integer"
      idProfessor:
        type: "integer"
      CFU: 
        type: "integer"
    required: 
      - idCourse
      - idProfessor
      - CFU
    example: 
      idCourse: 87498
      idProfessor: 3798218
      CFU: 12
  
  Deliveries:
    type: "object"
    properties:
      idDelivery:
        type: "integer"
      idStudent:
        type: "integer"
      idExam:
        type: "integer"
      answers:
        type: "array"
        items: 
          type: "string"
      timeDelivery:
        type: "string"
        format: "date-time"
        
    required:
      - idDelivery
      - idStudent
      - idExam
      - answers
      - timeDelivery
    
    example:
      idDelivery: 8749387
      idStudent: 3346896
      idExam: 78997667
      answer: array
      deadline: "2018-12-13 15:02:30"